{% set python_min = '3.10' %}
{% set name = "remotebmi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/remotebmi-{{ version }}.tar.gz
  sha256: 396a37f126df7207f12d16874130e0d490e51065f58c7c2faa45bb10a5ce863f

build:
  entry_points:
    - run-bmi-server = remotebmi.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - bmipy
    - numpy
    - httpx >=0.27.2
    - connexion
    - uvicorn
    - docker-py

test:
  imports:
    - remotebmi
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Basic Model Interface over openapi specification
  dev_url: https://github.com/eWaterCycle/remotebmi
  home: https://github.com/eWaterCycle/remotebmi
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - BSchilperoort
    - RolfHut
